master:
  port: 4000

secondaries:
  - url: http://secondary1:3001
    name: secondary1
    delay: 0
  - url: http://secondary2:3002
    name: secondary2
    delay: 5000

replication:
  secondaryDelay: 10000
